---
- name: Gather Facts From Switch
  hosts: switches
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Gathering Facts from {{ inventory_hostname}}
    ios_facts:
      gather_subset: min
    register: collected_facts

  - name: Print the Facts Info
    debug:
      var: collected_facts

  - name: Issue Command
    ios_command:
      commands:
      - show run | in username
    register: local_users

  - name: Print Local Users Configured
    debug:
      var: local_users['stdout'][0]

  - name: Saving to a File
    template:
      src: snmp.j2
      dest: ./files/{{ inventory_hostname }}.cfg
  
  - name: GENERATE DEVICE SPECIFIC REPORTS
    template:
      src: ./report.j2
      dest: ./files/reports/{{ inventory_hostname }}.md

  - name: CREATE MASTER REPORT
    assemble:
      src: ./files/reports/
      dest: ./files/master-report.md
      delimiter: "---"
    run_once: true
   
